apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev-apps
  namespace: argocd
  labels:
    tier: root
    env: dev
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  description: Development applications
  destinations:
    - name: "*"
      namespace: dev
      server: "*"
  sourceRepos:
    - git@github.com:pienczyk/codedump.git
