apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prod-apps
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  description: Production applications
  destinations:
    - name: "*"
      namespace: prod
      server: "*"
  sourceRepos:
    - git@gitlab.com:pienczyk/codedump.git
