apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# List of resources to include in the customization.

resources:
  # Path to the base directory containing configuration files.
  - ./namespace.yaml
  - ./configMap.yaml
  - ../../base
  - ../../components/db

# namespace
namespace: dev

# Prefix and suffix to be added to names of resources.
namePrefix: dev-
# nameSuffix: -dev

# Common labels to be applied to all resources.
commonLabels:
  env: dev

# Common annotations
commonAnnotations:
  branch: dev
  node: superNode

# Images
#images:
#  - name: nginx
#    newName: httpd
#    newTag: alpine3.20

# Patches
# PatchesStrategicMerge
# Separate file for patch
patchesStrategicMerge:
  - ./web-server-patch.yaml

# Patches Json6902
# Inline
patches:
  # Change deployment name
  - target:
      kind: Deployment
      name: web-server
    patch: |-
      - op: replace
        path: /metadata/name
        value: httpd

  # Remove the app tag
  - target:
      kind: Deployment
      name: web-server
    patch: |-
      - op: remove
        path: /metadata/labels/maintainer
