---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
spec:
  template:
    spec:
      containers:
        - name: web-server
          resources:
            requests:
              cpu: 200m
            limits:
              cpu: 300m
