apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# List of resources to include in the customization.
resources:
  # Path to the base directory containing configuration files.
  - ./namespace.yaml
  - ./configMap.yaml
  - ../../base
  - ../../components/db
  - ../../components/caching

# namespace
namespace: prod

# Prefix to be added to names of resources.
namePrefix: prod-

# Common labels to be applied to all resources.
commonLabels:
  env: production

# Patches
# PatchesStrategicMerge
# Separate file for patch
patchesStrategicMerge:
  - ./container_cpu.yaml
  - ./web-server-patch.yaml

# Inline
# Patches Json6902
patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: web-server
      spec:
        template:
          metadata:
            labels:
              modifyed_by: kustomize

  - target:
      kind: Deployment
      name: web-server
    patch: |-
      - op: replace
        path: /spec/strategy/rollingUpdate/maxSurge
        value: 10%

  # Separate file for patch
  - target:
      group: apps
      version: v1
      kind: Deployment
    path: replica_count.yaml
