---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: web-server
  type: ClusterIP
  ports:
    - name: web-service-port
      protocol: TCP
      port: 80
      targetPort: 80
