---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
spec:
  template:
    spec:
      containers:
        - name: web-server
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: index-cm-vol
      restartPolicy: Always
      volumes:
        - name: index-cm-vol
          configMap:
            name: qa-index-html
