# Deployment with the ingress

# ConfigMap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-deployment-04-cm
  namespace: playground
data:
  index.html: |
    Welcome from the ConfigMap and Ingress

# Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment-04
  namespace: playground
  labels:
    kind: deployment
spec:
  selector:
    matchLabels:
        app: ingress-app
  template:
    metadata:
      name: app-deployment-04
      labels:
        app: ingress-app
    spec:
      containers:
        - name: app-deployment-04
          image: nginx:alpine3.18
          resources:
            requests:
              memory: "50Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "1"
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: app-deployment-04-v
      volumes:
        - name: app-deployment-04-v
          configMap:
            name: app-deployment-04-cm

# Service
---
apiVersion: v1
kind: Service
metadata:
  name: app-deployment-04-svc
  namespace: playground
spec:
  selector:
    app: ingress-app
  ports:
  - port: 80
    targetPort: 80


# Ingress
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-deployment-04-ing
  namespace: playground
  labels:
    app: ingress-app
    kind: ingress
spec:
  rules:
  - host: ingress.testowy.org
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: app-deployment-04-svc
            port:
              number: 80
