apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# List of resources to include in the customization.
resources:
  # Path to the base directory containing configuration files.
  - ./namespace.yaml
  - ./configMap.yaml
  - ../../base
  - ../../components/db

# namespace
namespace: stage

# Prefix and suffix to be added to names of resources.
namePrefix: stage-

# Common labels to be applied to all resources.
commonLabels:
  env: stage

# Patches
# PatchesStrategicMerge
patchesStrategicMerge:
  - ./web-server-patch.yaml
