name: Build and deploy Webapp UI

on:
  workflow_dispatch:

jobs:
  build_app:
    runs-on: ubuntu-latest
    name: Build the app
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Setup bun      
    # Setup bun package manager
    - name: Setup bun package manager
      id: setup-bun
      run: |
        curl -fsSL https://bun.sh/install | bash -s "bun-v1.1.29"
        export BUN_INSTALL="$HOME/.bun"
        export PATH="$BUN_INSTALL/bin:$PATH"
        # echo "Installed bun version: $(bun --version)"
        # source $HOME/.bashrc
        echo $PATH
        
      # if [ -d "$HOME/.bun" ]; then
      # CURRENT_VERSION=$(bun --version)
      # DESIRED_VERSION="1.1.29"
      # if [ "$CURRENT_VERSION" != "$DESIRED_VERSION" ]; then
      #   echo "Updating Bun from $CURRENT_VERSION to $DESIRED_VERSION..."
      #   rm -rf "$HOME/.bun" # Optional: Remove existing installation
      #   curl -fsSL https://bun.sh/install | bash -s "$DESIRED_VERSION"
      # else
      #   echo "Bun is already up to date ($CURRENT_VERSION)."
      #   fi
      # else
      #   curl -fsSL https://bun.sh/install | bash -s "bun-v1.1.29"
      # fi
      #   if [ ! -d "$HOME/.bun" ]; then
      #     curl -fsSL https://bun.sh/install | bash -s "bun-v1.1.29"
      #   fi
      #   export BUN_INSTALL="$HOME/.bun"
      #   export PATH="$BUN_INSTALL/bin:$PATH"
      #   echo "Installed bun version: $(bun --version)"

        # echo "Create cache directories"
        # mkdir -p ${{ github.workspace }}/.bun/cache
        # mkdir -p ./apps/hello-bun/node_modules

    # Cache bun installation
    # - name: Cache modules
    #   id: cache-modules
    #   uses: actions/cache@v4
    #   with:
    #     path: |
    #       ${{ github.workspace }}/.bun/cache
    #       ./apps/hello-bun/node_modules
    #     key: ${{ runner.os }}-webui-${{ hashFiles('**/bun.lockb') }}
    #     # key: ${{ runner.os }}-webui-${{ hashFiles('**/bun.lockb') }}-${{ steps.cache-modules.outputs.cache-hit }}
    #     restore-keys: |
    #       ${{ runner.os }}-webui-

    # Build the SPA bun
    - name: Build the app
      run: |
        echo $PATH
        # cd ./apps/hello-bun
        # # BUN_INSTALL="$HOME/.bun"
        # # export PATH="$BUN_INSTALL/bin:$PATH"
        # bun --version
        # bun install
        # bun run build
        
     
