name: Build and deploy Webapp UI

on:
  workflow_dispatch:

jobs:
  build_app:
    runs-on: ubuntu-latest
    name: Build the app
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Setup bun      
    # Setup bun package manager
    - name: Setup bun package manager
      id: setup-bun
      run: |
        if [ ! -d "$HOME/.bun" ]; then
          curl -fsSL https://bun.sh/install | bash -s "bun-v1.1.27"
        fi
        export BUN_INSTALL="$HOME/.bun"
        export PATH="$BUN_INSTALL/bin:$PATH"

    # - name: Install dependencies
    #   run: |
    #     BUN_INSTALL="$HOME/.bun"
    #     export PATH="$BUN_INSTALL/bin:$PATH"
    #     cd ./apps/hello-bun
    #     bun install
        
    # # Cache bun installation
    # - name: Cache modules
    #   id: cache-modules
    #   uses: actions/cache@v4
    #   with:
    #     path: ./apps/hello-bun/node_modules
    #     key: ${{ runner.os }}-webui-${{ hashFiles('**/bun.lockb') }}
    #     restore-keys: |
    #       ${{ runner.os }}-webui-

    # Build the SPA bun
    - name: Build the app
      run: |
        cd ./apps/hello-bun
        BUN_INSTALL="$HOME/.bun"
        export PATH="$BUN_INSTALL/bin:$PATH"
        bun install
        bun run build
        
     
