name: image-ci

# When action should run
on:
  push:
    tags:
      - "*"
  workflow_dispatch:

env:
  image_name: "pienczyk/ghapp-njs-01"

jobs:
  build-tag-push:
    runs-on: ubuntu-latest
    steps:
      # Checkout self to a runner
      - name: Checkout
        uses: actions/checkout@v4

      # Install QEMU static binaries.
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Set up Docker Buildx.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to the Docker Hub. Secrets are configured in the GitHub/repository/settings/secrets/actions
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build, tag and push

      # yt-2-mp3
      # Build metadata for yt-2-mp3 image
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.image_name }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern=v{{version}}

      # Build and push yt-2-mp3 to the Docker hub
      - name: Build and push
        id: build_and_push
        uses: docker/build-push-action@v5
        with:
          file: apps/ghapp-njs-01/Dockerfile
          context: apps/ghapp-njs-01/
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64
          push: true

      # Scan the image with Trivy vulnerability scanner
      - name: Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ env.image_name }}:latest"
          format: "table"
          exit-code: "0"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL, HIGH"

      - name: Modify deployment
        run: |
          FIRST_TAG=$(echo "${{ steps.meta.outputs.tags }}" | cut -d',' -f1)
          echo $FIRST_TAG
          #sed -i 's/[0-9]\+\.[0-9]\+\.[0-9]\+/$FIRST_TAG/g' $DEPLOYMENT_FILE
        env:
          DEPLOYMENT_FILE: "apps/ghapp-njs-01/ghapp-njs-01.yaml"

          #- name: Push new deployment file
          #  run: |
          #    git config --local user.name "github-actions"
          #    git config --local user.email "github-actions@github.com"
          #    git switch $DEPLOYMENT_BRANCH
          #    git add $DEPLOYMENT_FILE
          #    git push origin $DEPLOYMENT_BRANCH
          #  env:
          #    DEPLOYMENT_FILE: "apps/ghapp-njs-01/ghapp-njs-01.yaml"
          #    DEPLOYMENT_BRANCH: "ghapp-njs-01"
          #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
