name: Build, test and push the OCI image

on:
  workflow_dispatch:


jobs:
    # Build, tag and push the image
    build_and_push:
      runs-on: ubuntu-latest
      defaults:
        run:
          shell: bash
      env:
        IMAGE_NAME: custom-nginx
        DOCKER_REPO: pienczyk


      steps:
        # Checkout self to a runner
        - name: Checkout
          uses: actions/checkout@v4

        # Install QEMU static binaries.
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3

        # Set up Docker Buildx.
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
          
        # Genereate timestamp tag
        - name: Generate timestamp tag
          id: timestamp
          run: echo "DATE_TAG=$(date +'%Y%m%d')" >> $GITHUB_ENV

        # Build metadata image
        - name: Docker metadata
          id: meta
          uses: docker/metadata-action@v5
          with:
            flavor: |
              latest=true
              prefix=${{ env.DATE_TAG }}-
            images: |
              ${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}
            tags: |
              type=raw,value=${{ github.run_id }}${{ github.run_number }}
              type=sha,enable=true,format=short

        - name: Build
          uses: docker/build-push-action@v6
          with:
            file: apps/oci-build/Dockerfile
            context: apps/oci-build/
            tags: ${{ steps.meta.outputs.tags }}
            load: true

        - name: Test
          run: |
            IMAGE_TAG=$(echo "${{ steps.meta.outputs.tags }}" | cut -d ',' -f1) && IMAGE_TAG=$(echo $IMAGE_TAG | cut -d ':' -f2) && echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV 
            echo "Running Docker image with tag: $IMAGE_TAG"
            docker run --rm ${{ env.IMAGE_NAME }}:$IMAGE_TAG  