name: Test the workflow triggers

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - closed
    branches:
      - main  # or the branch where PRs are merged
    paths:
      - 'test_path/**'  # Only trigger if files in the `test_path/` directory are changed

jobs:
  dev:
    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize' || (github.event.action == 'closed' && github.event.pull_request.merged == true))
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Print the changed files
        run: |
          echo "Running on DEV"

  test:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    needs: dev
    runs-on: ubuntu-latest
    environment: stage

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Print the changed files
        run: |
          TAG_NAME=${{ env.DATE_TAG }}-${{ github.run_id }}${{ github.run_number }}
          echo "Running on TEST"
          echo "Generated tag: ${TAG_NAME}"
  prod:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    needs: test
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Print the changed files
        run: |
          echo "Running on PROD"
