# .github/workflows/main-workflow.yml

name: Test the workflow triggers

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - closed
    branches:
      - main  # or the branch where PRs are merged
    paths:
      - 'test_path/**'  # Only trigger if files in the `test_path/` directory are changed

jobs:
  dev:
    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize' || (github.event.action == 'closed' && github.event.pull_request.merged == true))
    uses: ./.github/workflows/template-echo.yml
    with:
      environment: dev

  test:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    needs: dev
    uses: ./.github/workflows/template-echo.yml
    with: 
      environment: stage
      
  prod:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    needs: test
    uses: ./.github/workflows/template-echo.yml
    with:
      environment: prod
