# .github/workflows/main-workflow.yml

name: Test the workflow triggers

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - closed
    branches:
      - main  # or the branch where PRs are merged
    paths:
      - 'test_path/**'  # Only trigger if files in the `test_path/` directory are changed

jobs:
  dev:
    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize' || (github.event.action == 'closed' && github.event.pull_request.merged == true))
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v4
      - name: Run Common Steps
        uses: ./.github/workflows/template-echo.yml
        with:
          environment: dev

  test:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    needs: dev
    runs-on: ubuntu-latest
    environment: stage

    steps:
      - uses: actions/checkout@v4
      - name: Run Common Steps
        uses: ./.github/workflows/template-echo.yml
        with:
          environment: stage

  prod:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    needs: test
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - uses: actions/checkout@v4
      - name: Run Common Steps
        uses: ./.github/workflows/template-echo.yml
        with:
          environment: prod
