name: Test the workflow triggers

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
  pull_request:
    types:
      - opened
      - synchronize
      - closed
    branches:
      - main  # or the branch where PRs are merged
    paths:
      - 'test_path/**'  # Only trigger if files in the `stage_path/` directory are changed

jobs:
  dev:
    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize' || (github.event.action == 'closed' && github.event.pull_request.merged == true)) || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/template-echo.yml
    with:
      environment: dev
      agent_version: ubuntu-latest

  stage:
    if: (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true) || github.event_name == 'workflow_dispatch'
    needs: dev
    uses: ./.github/workflows/template-echo.yml
    with: 
      environment: stage
      agent_version: ubuntu-latest
      
  prod:
    if: (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true) || github.event_name == 'workflow_dispatch'
    needs: stage
    uses: ./.github/workflows/template-echo.yml
    with:
      environment: prod
      agent_version: ubuntu-latest

  agent_dev:
    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize' || (github.event.action == 'closed' && github.event.pull_request.merged == true)) || github.event_name == 'workflow_dispatch'
    needs: dev
    uses: ./.github/workflows/template-agent-info.yml
    with:
      environment: dev
      agent_version: ubuntu-latest

  agent_stage:
    if: (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true) || github.event_name == 'workflow_dispatch'
    needs: stage
    uses: ./.github/workflows/template-agent-info.yml
    with:
      environment: stage
      agent_version: ubuntu-latest
      
  agent_prod:
    if: (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true) || github.event_name == 'workflow_dispatch'
    needs: prod
    uses: ./.github/workflows/template-agent-info.yml
    with:
      environment: prod
      agent_version: ubuntu-latest
